services:
  - type: web
    name: medikiosk
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///patient_case.db
      - key: FLASK_ENV
        value: production